baseURL = "https://pylory.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "Pylory's Blog"
theme = "hugo-theme-diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "nord"
    tabWidth = 4


[taxonomies]
   category = "categories"
   tag = "tags"

[[menu.main]]
url = "/posts"
name = "存档"
weight = 1

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "/categories"
name = "分类"
weight = 3
